# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-12 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0004_auto_20190712_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='图片标题')),
                ('width', models.FloatField(verbose_name='宽度')),
                ('height', models.FloatField(verbose_name='高度')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='图片上传时间')),
                ('url', models.FileField(upload_to='%Y/%m/%d', verbose_name='图片url')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Manager', verbose_name='图片作者')),
            ],
            options={
                'db_table': 'Media',
            },
        ),
    ]
