# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-03 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('column', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='文章标题')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('image', models.ImageField(default='null', upload_to='static/images', verbose_name='特色图片')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('markdown', models.TextField(default='', verbose_name='markdown')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('introduction', models.CharField(max_length=500, verbose_name='摘要')),
                ('publicStatus', models.CharField(max_length=50, verbose_name='发布状态')),
                ('commentStatus', models.BooleanField(verbose_name='是否开启评论')),
                ('commentId', models.IntegerField(default=0, verbose_name='评论')),
                ('url', models.TextField(verbose_name='文章url')),
                ('column', models.ManyToManyField(null=True, to='column.Columns')),
            ],
            options={
                'db_table': 'Article',
            },
        ),
    ]
