# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-22 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('column', models.IntegerField(default=1)),
                ('introduction', models.CharField(max_length=500)),
                ('publicStatus', models.CharField(max_length=50)),
                ('commentStatus', models.BooleanField()),
                ('commentId', models.IntegerField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'Article',
            },
        ),
    ]
