# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-22 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='null', upload_to='static/images'),
        ),
    ]
