# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-03 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='column',
            field=models.ManyToManyField(to='column.Columns'),
        ),
    ]
