# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-04 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleManagement', '0002_auto_20190703_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='available',
            field=models.BooleanField(default=True, verbose_name='是否可用'),
        ),
    ]
