# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-26 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleManagement', '0004_auto_20190625_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='commentId',
            field=models.IntegerField(default=0, verbose_name='评论'),
        ),
    ]
