# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-27 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleManagement', '0005_auto_20190626_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='column',
            field=models.CharField(default=1, max_length=50, verbose_name='分类'),
        ),
    ]
