# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-02 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleManagement', '0007_article_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='文章标题'),
        ),
    ]
