# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-27 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articleManagement', '0006_auto_20190627_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('columnId', models.AutoField(primary_key=True, serialize=False, verbose_name='columnId')),
                ('parent', models.IntegerField(default=0, verbose_name='父分类id')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('articles', models.ManyToManyField(to='articleManagement.Article')),
            ],
            options={
                'db_table': 'Columns',
            },
        ),
    ]
