# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-27 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='columns',
            name='name',
            field=models.CharField(default='0', max_length=100, verbose_name='分类名称'),
        ),
    ]
