# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-14 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='permission',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
