# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-12 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190614_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='manager',
            table='Manager',
        ),
    ]
