# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-12 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20190712_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
